version: '3.8'

services:
  vue-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-gestion-tribunaux
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - mongodb
      - sonarqube

  vue-frontend-preprod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80" # Préprod (accessible sur localhost:4000)
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - mongodb

  vue-frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80" # Prod (accessible sur localhost:5000)
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_WEB_HOST=0.0.0.0
      - SONAR_WEB_PORT=9000
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
